version: '3'

x-db-env: &db-env
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: proxypics123

x-db-base: &db-base
  image: postgres:12.10-alpine
  healthcheck:
    test: ['CMD-SHELL', 'pg_isready -U postgres']
    interval: 10s
    timeout: 10s
    retries: 5

services:
  server:
    container_name: proxypics_challenge_server
    build:
      context: ./server
    restart: unless-stopped
    entrypoint: /app/entrypoint.sh
    env_file: ./server/env-example
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  nginx:
    container_name: proxypics_challenge_development_nginx
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
  db:
    <<: *db-base
    container_name: proxypics_challenge_development_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      <<: *db-env
      POSTGRES_DB: proxypics_challenge_development

  db_test:
    <<: *db-base
    container_name: proxypics_challenge_test_db
    environment:
      <<: *db-env
      POSTGRES_DB: proxypics_challenge_test

volumes:
  postgres_data: